<a href="https://colab.research.google.com/github/ManelSoengas/Pytorch/blob/main/Pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensor**

---

Un tensor és una estructura matemàtica que generalitza els escalars, vectors i matrius a dimensions més altes. En el context de la programació i la intel·ligència artificial (especialment en biblioteques com TensorFlow o PyTorch), un tensor és essencialment una taula multidimensional de dades numèriques.

In [1]:
import torch
import numpy as np

**Inicialitzant un tensor**

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
data

[[1, 2], [3, 4]]

**Des de Numpy array**

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**Des d'un altre tensor**

In [8]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6798, 0.2906],
        [0.7776, 0.9287]]) 



**Omplir un tensor amb random valors i nombres**

In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7522, 0.4031, 0.2475],
        [0.2223, 0.0070, 0.1665]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


**Atributs d'un tensor**

In [10]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
tensor

tensor([[0.6001, 0.6194, 0.4541, 0.6782],
        [0.4715, 0.0519, 0.5202, 0.8812],
        [0.7958, 0.7724, 0.6806, 0.9209]])

**Operacions amb tensors**

In [12]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

**Indexació i tall estàndard de tipus numpy:**

In [15]:
tensor = torch.ones(5, 5)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -11])
tensor[:,2] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1., 1.])
tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])


**Unint tensors**

In [17]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.]])


**Operacions Aritmètiques**

In [18]:
# @ és un operador que fa producte matricial (dot product) entre tensor i la seva transposada tensor.T.
# Si tensor és de forma (2, 2), tensor.T també serà (2, 2), així que y1 serà també (2, 2).
# funció explícita matmul() en lloc del símbol @

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])

In [19]:
y3

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])

In [20]:
tensor

tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])

**Elements simples d'un tensor**

In [21]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

20.0 <class 'float'>


In [22]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]]) 

tensor([[6., 6., 5., 6., 6.],
        [6., 6., 5., 6., 6.],
        [6., 6., 5., 6., 6.],
        [6., 6., 5., 6., 6.],
        [6., 6., 5., 6., 6.]])
